const hr_chat_data = [
  {
    "employeeName": "Muthair",
    "designation": "Software Engineer",
    "timeStamp": "2023-07-08T12:35:56Z",
    "employeeId": 3186,
    "aspNetUserId": 2331,
    "profile": "https://",
    "message": "Hi How are you",
  },
  {
    "employeeName": "Abdul Mateen",
    "designation": "Software Engineer",
    "timeStamp": "2023-07-08T12:35:56Z",
    "employeeId": 1234,
    "aspNetUserId": 1122,
    "profile": "https://",
    "message": "Hi How are you",
  },
  {
    "employeeName": "Abdul Mateen",
    "designation": "Software Engineer",
    "timeStamp": "2023-07-08T12:35:56Z",
    "employeeId": 1234,
    "aspNetUserId": 1122,
    "profile": "https://",
    "message": "Hi How are you",
  },
  {
    "employeeName": "Abdul Mateen",
    "designation": "Software Engineer",
    "timeStamp": "2023-07-08T12:35:56Z",
    "employeeId": 1234,
    "aspNetUserId": 1122,
    "profile": "https://",
    "message": "Hi How are you",
  },
  {
    "employeeName": "Abdul Mateen",
    "designation": "Software Engineer",
    "timeStamp": "2023-07-08T12:35:56Z",
    "employeeId": 1234,
    "aspNetUserId": 1122,
    "profile": "https://",
    "message": "Hi How are you",
  },
  {
    "employeeName": "Abdul Mateen",
    "designation": "Software Engineer",
    "timeStamp": "2023-07-08T12:35:56Z",
    "employeeId": 1234,
    "aspNetUserId": 1122,
    "profile": "https://",
    "message": "Hi How are you",
  }
];
