/// notifications : [{"title":"Leave Application Submitted","message":"Leave request has been generated by Kamran Saif","createdDateTime":"2024-07-04T17:56:20.063628","type":"asdasda"}]
/// isError : false

class NotificationsModel {
  NotificationsModel({
      List<Notifications>? notifications, 
      bool? isError,}){
    _notifications = notifications;
    _isError = isError;
}

  NotificationsModel.fromJson(dynamic json) {
    if (json['notifications'] != null) {
      _notifications = [];
      json['notifications'].forEach((v) {
        _notifications?.add(Notifications.fromJson(v));
      });
    }
    _isError = json['isError'];
  }
  List<Notifications>? _notifications;
  bool? _isError;
NotificationsModel copyWith({  List<Notifications>? notifications,
  bool? isError,
}) => NotificationsModel(  notifications: notifications ?? _notifications,
  isError: isError ?? _isError,
);
  List<Notifications>? get notifications => _notifications;
  bool? get isError => _isError;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    if (_notifications != null) {
      map['notifications'] = _notifications?.map((v) => v.toJson()).toList();
    }
    map['isError'] = _isError;
    return map;
  }

}

/// title : "Leave Application Submitted"
/// message : "Leave request has been generated by Kamran Saif"
/// createdDateTime : "2024-07-04T17:56:20.063628"
/// type : "asdasda"

class Notifications {
  Notifications({
      String? title, 
      String? message, 
      String? createdDateTime, 
      String? type,}){
    _title = title;
    _message = message;
    _createdDateTime = createdDateTime;
    _type = type;
}

  Notifications.fromJson(dynamic json) {
    _title = json['title'];
    _message = json['message'];
    _createdDateTime = json['createdDateTime'];
    _type = json['type'];
  }
  String? _title;
  String? _message;
  String? _createdDateTime;
  String? _type;
Notifications copyWith({  String? title,
  String? message,
  String? createdDateTime,
  String? type,
}) => Notifications(  title: title ?? _title,
  message: message ?? _message,
  createdDateTime: createdDateTime ?? _createdDateTime,
  type: type ?? _type,
);
  String? get title => _title;
  String? get message => _message;
  String? get createdDateTime => _createdDateTime;
  String? get type => _type;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['title'] = _title;
    map['message'] = _message;
    map['createdDateTime'] = _createdDateTime;
    map['type'] = _type;
    return map;
  }

}